### PR TITLE
Fix typo in README.md, set up develpment dependencies for testing.

### PR DESCRIPTION
**Pull request by shadefinale**

### CODE REVIEW

**Comment by kurenn** [comment]
Can you drop some specs as examples of what you think should be tested?

**Comment by shadefinale** [comment]
I have written an example test in `spec/will_paginate_extension_spec.rb`. I initially tried an approach of mocking out a controller and have hit a wall in that attempt after slowly crawling my way near a solution, so instead I wrote a DummyCtrl and DummyRequest to mock out all the things that `paginate` seems to need to write an example spec.

This is not ideal and I'm pretty sure there's a better way to make changes so if you have any suggestions on how to make the test in `spec/controllers/page_spec.rb` that should be the way to go.

**Comment by shadefinale** [comment]
I've written another spec that tests the defining of a `per_page` directly on the model when using the `will_paginate` gem.

Will Paginate allows something like this:
```
# for the Post model
class Post
  self.per_page = 10
end
```

And I've added a test and modifed `lib/pagination/will_paginate.rb` to allow this test to pass by directly checking for the collection's `per_page` before defaulting to `::WillPaginate`.

**Comment by kurenn** [comment]
Looks promising!, the mocking idea does not sound bad, but maybe you can include some actual action controllers, just to not mock everything around..

What do you think?

**Comment by shadefinale** [comment]
I'll be honest, I haven't figured out how to do that. As I mentioned, `spec/controllers/page_spec.rb` actually has a test that was beginning to try and do that, but I can't seem to actually create an anonymous controller in the test so it's just stuck at that point.

**Comment by kurenn** [comment]
Are we having any progress on this?

**Pull request closed without merging**
