### PR TITLE
Adds support for pagy

### PR DESCRIPTION
**Pull request by kurenn**
### What does this PR do?

* Adds pagy support
* Fixes a duplicate variable name for configuration
* Improves the loading for the pager configuration for each pager

### CODE REVIEW

**Comment by ddnexus** [comment]
@kurenn a couple of things:

- I see that the `:page` param is hard-coded in the params merge. Is that the standard way for headers and links, regardless the fact that the page might be passed around as a different param name, or the param `:page` is the only supported? 
- The PR doesn't seem to update the README

**Comment by kurenn** [comment]
@ddnexus 

* You are right about the hard-coded params, maybe we can add a `page_param_name` as a configuration option, in case someone decides to customize it, maybe on another PR?
* Sure, I will update that, I was just to excited to see it working I just push the code

**Comment by ddnexus** [comment]
Yup! I received explicit requests for that feature in PAgy, and it is available for WillPaginate and Kaminari too. Here is the code that handle that in Pagy:

```ruby
def pagy_url_for(page, pagy)
  p_vars = pagy.vars; params = request.GET.merge(p_vars[:page_param] => page, **p_vars[:params])
  "#{request.path}?#{Rack::Utils.build_nested_query(pagy_get_params(params))}#{p_vars[:anchor]}"
end
```

**Comment by ddnexus** [comment]
@cseelus can add more details about the use cases...

**Comment by cseelus** [comment]
From a (resolved) Pagy issue:

The ability to add arbitrary params similar to [will_paginates :params option](https://github.com/mislav/will_paginate/wiki/API-documentation#will_paginatecollection-options) or [Kaminaris option with the same name](https://github.com/kaminari/kaminari#extra-parameters-params-for-the-links) would be helpful for a number of use cases:

- […] (not applicable for API pagination)
- Passing search/form params around, when Pagy is used in combination with a search function
- Passing in a controller/action name (see will_paginate or Kaminaris docs)

**Comment by kurenn** [comment]
Thanks for all the feedback @ddnexus and @cseelus, I'll keep working on this but just focusing on the pagy support as it is, and then on another PR I can work on the dynamic param method, how does that sound. 

I will create an issue for that

**Comment by cseelus** [comment]
@kurenn Pagy support does work nicely btw, tested it locally with a production Rails app + Postman as well as an iOS app that consumes the apps API.

Thanks so far!

**Comment by cavi21** [comment]
hi everyone! wondering if there is a plan to merge this into master before the #24 is closed? because as @cseelus said _Pagy support does work nicely btw_ so maybe this could be merge.

Also if I can help with it or to look into something, count with me :)
Thanks! awesome work

**Comment by kurenn** [comment]
I think this PR is ready to merge, I updated the README, I'm creating a new issue regarding the `:page` param name to be dynamic as suggested by @ddnexus

**Comment by csaurav** [comment]
Any update on this ? Will this be merged ?

**Comment by kurenn** [comment]
It is done @csaurav ! :tada: sorry for the delay! the version is `0.3.0`

**Pull request merged**
